### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by tugapower0** [zRxnx/zrx_armour#1]
This is not a issue but rather a feature you could add, that would make more realistic, if the player armour is = 100 ( full armour ) instead of using another vest, remove the one it have and setup player with armour = 0 and return the vest to inventory. If the armour is less then 100 then use another armour. Or maybe a command to check if player armour is = 100 and return the item to inventory.
What you think @zRxnx ?

**Comment by tugapower0** [comment]
Also on a side note, if we spam the use of vest it get triggered the Config.PunishPlayer(source, 'Tried to trigger "zrx_armour:server:useArmour"') , maybe it needs a better aproach this part.

**Comment by zRxnx** [comment]
So instead setting the armour value on join, give a item with the armour value?

**Comment by tugapower0** [comment]
Not relative to join, let say equip a vest, my armour will be 100, if equip another, it will equip on top of an already full armour, instead of equiping, if you press to use a vest and your actual vest is 100, instead of equip remove the one you have and give vest again to inventory. Hope you understand now.

**Comment by zRxnx** [comment]
I've been thinking about this again. I don't think there is a good way to implement this without a new database entry.

**Comment by tugapower0** [comment]
Well, actually you don't need database for this part, when the player use the item, it does a check first, if player armour it's full, it set the ped with armour 0 and it gives to inventory the armour. If the ped armour is less then 100 it uses the item and set the ped with armour full. Did implemented on my case like this, don't think it's perfect, but does the job, will detail here latter when at home on pc how did this without using database.

**Comment by zRxnx** [comment]
If the player has 79 armour, and he wants to use a new armour, the armour sets to 100.
If the player has 100 armour and he wants to use a new armour, it sets to 0 and he gets a 100 armour back as item?

**Comment by tugapower0** [comment]
Yes, exactly like that. The only inconvenient it's the player need to have at least one armour on inventory if he want to remove the one it have if it's full armour equipped. That's why to by pass this limit think it's a good idea to also implement a command.

**Comment by zRxnx** [comment]
And how should you detect which armour he should get?

**Comment by tugapower0** [comment]
indeed, forget about the various vests, probably a new champ on database saying the vest it have equiped ?

**Comment by tugapower0** [comment]
Altough on my case, since it returns the vest its using with the item, its ok for me to use like this. But indeed a databse saving the type of vest player is using its probably the best aproach.

**Comment by tugapower0** [comment]
You already have that before, think it was called index on database? No ?

**Comment by zRxnx** [comment]
Removed that, because config indexes can change

**Comment by zRxnx** [comment]
Possible with https://github.com/zRxnx/zrx_armour/releases/tag/2.4.0
