### ISSUE TITLE
Bulletproof vests aren't being registered as items. [ESX]

### ISSUE THREAD

**Issue by yiruzu** [zRxnx/zrx_armour#10]

**Comment by zRxnx** [comment]
do you use ox_inv?

**Comment by yiruzu** [comment]
> do you use ox_inv?

No I also set it to default in the config

**Comment by zRxnx** [comment]
also in the utility?

**Comment by yiruzu** [comment]
> also in the utility?
> 
> 

Yes

**Comment by yiruzu** [comment]
@zRxnx

**Comment by tugapower0** [comment]
Having the same issue, using esx legacy latest + qs-inventory

**Comment by zRxnx** [comment]
Still with the newest version?

**Comment by tugapower0** [comment]
Tested with 2.4.2. Did not tested with 2.5.0

**Comment by zRxnx** [comment]
Should work now properly
