### ISSUE TITLE
 No such export useItem in resource 

### ISSUE THREAD

**Issue by JeyCraft** [zRxnx/zrx_armour#11]
Greetings, did a fresh install of your script and when i try use the items i got this issue

[ script:ox_inventory] SCRIPT ERROR: @ox_inventory/modules/items/shared.lua:3: No such export useItem in resource zrx_armour
[ script:ox_inventory] 

The Items are written like this

	  ['bulletproof_small'] = { --  Use to set body armor to 25%
	  label = 'Light Ballistic Vest',
	  weight = 3000,
	  stack = false,
	  description = "Bullts hurt a bit less with this",
	  server = {
		export = 'zrx_armour.useItem'
	}
	  },

	  ['bulletproof_medium'] = { --  Use to set body armor to 50%
	  label = 'Medium Ballistic Vest',
	  weight = 4500,
	  stack = false,
	  description = "Bullets hurt a lot less with this",
	  server = {
		export = 'zrx_armour.useItem'
	}
	  },

	  ['bulletproof_big'] = { --  Use to set body armor to 75%
	  label = 'Heavy Ballistic Vest',
	  weight = 4500,
	  stack = false,
	  description = "Keep the extra bullets for personal vest flair",
	  server = {
		export = 'zrx_armour.useItem'
	}
	  },

**Comment by zRxnx** [comment]
Put it in discord, its easier to manage for me

**Comment by JeyCraft** [comment]
U got a Discord Direct Message. If its okay.

**Comment by zRxnx** [comment]
Dc server pls, dm is shit
