### ISSUE TITLE
Load vest entering server

### ISSUE THREAD

**Issue by tugapower0** [zRxnx/zrx_armour#3]
When player joins its not loading the vest altough on database its properly saved the player have vest.

**Comment by tugapower0** [comment]
Now it worked ...

**Comment by tugapower0** [comment]
Further tests will be done...

**Comment by tugapower0** [comment]
Ok, now did have time to test, for some reason its not loading the vest when a player have armour and enter the city, altough on database the player its indeed saved as it have armour.

**Comment by tugapower0** [comment]
![imagem](https://github.com/zRxnx/zrx_armour/assets/9769460/f0b00ad0-1c26-4a3d-bd30-bcfa2c85cea1)

**Comment by tugapower0** [comment]
when enters the city

![imagem](https://github.com/zRxnx/zrx_armour/assets/9769460/2c45e7e1-f6d8-441b-a355-fb13262787f6)

Its like is not restoring the armour when enters the city

**Comment by zRxnx** [comment]
You also have onesync infinity?

**Comment by tugapower0** [comment]
Yes, my server is using onesync infinity

**Comment by zRxnx** [comment]
Cant reproduce this

**Comment by zRxnx** [comment]
You have the same problem with the esx one. https://github.com/esx-framework/esx_core/issues/1233

Mine is server side, esx one is client side.
So ig you have a script that breaks that.

**Comment by tugapower0** [comment]
Don't think the problem it's the same, because esx should save health and armour on metadata and it's not saving at all data related to this. Also the only script that have taking care of this is es_extended that should save on table users on metada and yours that use its own table to save the armour.

**Comment by zRxnx** [comment]
Use latest version
