### ISSUE TITLE
Wrong Vest Id's will be displayed

### ISSUE THREAD

**Issue by JeyCraft** [zRxnx/zrx_armour#6]
When players Log off and come back they have another vest then setup in config on there models. Would be cool if you can check this. <3

**Comment by zRxnx** [comment]
Only the texture or an entire diffrent vest?

**Comment by JeyCraft** [comment]
Different.  atm its always the "1"  - Using illenium appearance if this maybe helps. (:

**Comment by zRxnx** [comment]
fixed in the coming update
