### ISSUE TITLE
Got a few errors when try take a vest on ):

### ISSUE THREAD

**Issue by JeyCraft** [zRxnx/zrx_armour#7]
![image](https://github.com/zRxnx/zrx_armour/assets/63811758/d6d15c19-e787-4e57-88f4-07e999cabf99)

Any ideas how to fix this?

**Comment by zRxnx** [comment]
Looks like you are missing some data, will look over it when i am at home.

Twchnically you could just remove the for temporarly

**Comment by JeyCraft** [comment]
Oh okay? did of all exept the config.lua a fresh install.

**Comment by zRxnx** [comment]
Fixed in the next update
